#!/usr/bin/env python

import liblo, sys,time
import DmxPy

# create server, listening on port 3000
try:
    server = liblo.Server(3000)
except liblo.ServerError, err:
    print str(err)
    sys.exit()

try:
    dmx = DmxPy.DmxPy('/dev/ttyUSB0')
except:
    print "Unable to open /dev/ttyUSB0"
    sys.exit()

def set(path, args):
    chan, val = args
    val = int(round(val))
    dmx.set(chan, val)
    dmx.render()
    print "DMX '%d' at '%d'" % (chan, val)

def blackout(path, args):
    dmx.setall(0)
    dmx.render()
    print "DMX all off"

def setall(path, args):
    if len(args) > 0:
        val = int(round(args[0]))
    else:
        val = 255
    dmx.setall(val)
    dmx.render()
    print "DMX all on"

# register methods
server.add_method("/dmx/set", 'ii', set)
server.add_method("/dmx/set", 'if', set)

server.add_method("/dmx/full", None, setall)
server.add_method("/dmx/setall", 'i', setall)

server.add_method("/dmx/off", None, blackout)
server.add_method("/dmx/blackout", None, blackout)

# loop and dispatch messages every 20ms
while True:
    server.recv(20)
